# Generated by Django 2.1.7 on 2019-03-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
