# Generated by Django 2.1.7 on 2019-04-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_follower'),
        ('articles', '0006_reportarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportArticle',
            new_name='Report',
        ),
    ]
