# Generated by Django 2.1.7 on 2019-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_comment_on_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_on_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_on_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
