# Generated by Django 2.1.7 on 2019-04-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_follower'),
        ('comments', '0003_auto_20190417_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.BooleanField()),
                ('comment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('liked_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
